AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-stepfunctions-apigw

  Sample SAM Template for sam-stepfunctions-apigw
  See https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-creating-lambda-state-machine.html

Globals:
  Function:
    Runtime: python3.9
    Architectures:
      - x86_64
    Timeout: 3
  Api:
    OpenApiVersion: 3.0.3

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/hello
      Handler: app.lambda_handler

  HelloFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: HelloFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${HelloFunction}"

  ResultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/result
      Handler: app.lambda_handler
      Events:
        Run:
          Type: Api
          Properties:
            Path: /result
            Method: post
      Policies:
        - Statement:
           - Effect: Allow
             Action: states:DescribeExecution
             Resource: !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:execution:${HelloStateMachine.Name}:*" # too long

  ResultFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: ResultFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub "/aws/lambda/${ResultFunction}"

  HelloStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/hello.asl.yaml
      DefinitionSubstitutions:
        HelloFunction: !GetAtt HelloFunction.Arn
      Type: STANDARD
      Events:
        Run:
          Type: Api
          Properties:
            Path: /run
            Method: post
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt HelloStateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ERROR
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref HelloFunction
        - Statement:
           - Effect: Allow
             Action:
               - logs:CreateLogDelivery
               - logs:GetLogDelivery
               - logs:UpdateLogDelivery
               - logs:DeleteLogDelivery
               - logs:ListLogDeliveries
               - logs:PutResourcePolicy
               - logs:DescribeResourcePolicies
               - logs:DescribeLogGroups
             # Resource: !GetAtt HelloStateMachineLogGroup.Arn
             Resource: "*"      # ↑を指定すると作成できない。理由不明

  HelloStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub
        - "/aws/vendedlogs/states/${AWS::StackName}-HelloStateMachine-${v1}-Log"
        - {v1: !Select [2, !Split [/, !Ref AWS::StackId ]]}

Outputs:
  HelloApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}"
